package com.cts.services.device.rest.controller;

/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */


import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.cts.services.device.rest.controller.vm.CarrierActivateRequest;
import com.cts.services.device.rest.controller.vm.RequestResponse;
import com.cts.services.device.rest.controller.vm.RestErrorResponse;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-03-07T06:18:11.724Z")

@Api(value = "devices", description = "the devices API")
public interface DevicesApi {

    @ApiOperation(value = "Activates service for one or more devices.", notes = "If the devices do not already exist in the account, this API method adds them before activation.", response = RequestResponse.class, tags={ "devices", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Request ID", response = RequestResponse.class),
        @ApiResponse(code = 400, message = "Error Response", response = RestErrorResponse.class) })
    
    @RequestMapping(value = "/devices/actions/activate",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<RequestResponse> activeUsingPOST(@ApiParam(value = "Activate request" ,required=true )  @Valid @RequestBody CarrierActivateRequest request,@ApiParam(value = "M2M-MC Session Token" ,required=true) @RequestHeader(value="VZ-M2M-Token", required=true) String vzM2MToken);

}
